// Generates src/artworks.generated.ts from artworks/*.json.
//
// Embedding the presets as one named `const` per artwork (instead of reading
// JSON at runtime) removes any node:fs dependency from library code, gives
// consumers compile-time `ArtworkSlug` types, and lets bundlers tree-shake the
// presets a consumer never imports. Run via `npm run codegen` (also part of
// `npm run build`).
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const packageRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const artworksDir = path.join(packageRoot, 'artworks');
const outFile = path.join(packageRoot, 'src', 'artworks.generated.ts');

// ES reserved words that pass the lowercase-alphanumeric slug check, plus the
// generated module's own exports.
const RESERVED_SLUGS = new Set([
  'break', 'case', 'catch', 'class', 'const', 'continue', 'debugger',
  'default', 'delete', 'do', 'else', 'enum', 'export', 'extends', 'false',
  'finally', 'for', 'function', 'if', 'implements', 'import', 'in',
  'instanceof', 'interface', 'let', 'new', 'null', 'package', 'private',
  'protected', 'public', 'return', 'static', 'super', 'switch', 'this',
  'throw', 'true', 'try', 'typeof', 'var', 'void', 'while', 'with', 'yield',
  'await', 'artworks', 'isartworkslug',
]);

const fileNames = (await readdir(artworksDir))
  .filter((fileName) => fileName.endsWith('.json'))
  .sort();

const artworks = await Promise.all(
  fileNames.map(async (fileName) => {
    const definition = JSON.parse(
      await readFile(path.join(artworksDir, fileName), 'utf-8')
    );
    const slug = fileName.replace(/\.json$/, '');

    if (definition.slug !== slug) {
      throw new Error(
        `artworks/${fileName}: "slug" is "${definition.slug}" but must match the file name`
      );
    }
    if (!/^[a-z][a-z0-9]*$/.test(slug)) {
      throw new Error(
        `artworks/${fileName}: slug must be a lowercase alphanumeric identifier`
      );
    }
    // Each slug becomes `export const <slug>`, so reserved words (and the
    // module's own identifiers) would generate a syntax/duplicate error.
    if (RESERVED_SLUGS.has(slug)) {
      throw new Error(
        `artworks/${fileName}: slug "${slug}" is a reserved identifier and cannot be used`
      );
    }

    return definition;
  })
);

const header = `// AUTO-GENERATED by scripts/codegen.mjs from artworks/*.json — do not edit.
// Regenerate with \`npm run codegen\` (runs automatically as part of \`npm run build\`).
import type { ArtworkDefinition } from './core/types.js';
`;

const consts = artworks
  .map(
    (definition) =>
      `export const ${definition.slug}: ArtworkDefinition = ${JSON.stringify(
        definition,
        null,
        2
      )};`
  )
  .join('\n\n');

const record = `export const artworks = {
${artworks.map(({ slug }) => `  ${slug},`).join('\n')}
} as const;

export type ArtworkSlug = keyof typeof artworks;

export function isArtworkSlug(value: string): value is ArtworkSlug {
  return Object.prototype.hasOwnProperty.call(artworks, value);
}
`;

await writeFile(outFile, `${header}\n${consts}\n\n${record}`);

console.log(
  `codegen: wrote ${artworks.length} artworks to ${path.relative(
    packageRoot,
    outFile
  )}`
);
