// Batch 1 (gallery orders 57-96): css-doodle.com sample variations + originals.
// Each def: vars = host-level custom props (rolled once per cell), rule = body of --rule.
// Conventions verified against css-doodle 0.51: solid colors / transforms / offsets /
// border-radius / clip-path(same arity) / box-shadow / opacity all transition on reseed;
// gradients are kept static or hidden beneath transforms.

export const batch1 = [
  {
    name: 'Prisma',
    slug: 'prisma',
    order: 57,
    white: true,
    description:
      'A full-bleed mosaic of half-square triangles in deep indigo and jewel tones — every reseed melts each facet into its next orientation.',
    palette: ['#1A1B3A', '#3E8BFF', '#3EECFF', '#FF3D8B', '#D89FFF', '#3FFFB2'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '6x6', frequency: 0.92 },
    vars: `/* Triangle orientation and ink roll once per cell; same-arity polygons morph between seeds */ --tri: @p(polygon(0% 0%, 100% 0%, 100% 100%), polygon(0% 0%, 100% 0%, 0% 100%), polygon(0% 0%, 100% 100%, 0% 100%), polygon(100% 0%, 100% 100%, 0% 100%)); --ink: @p(var(--color1), var(--color1), var(--color2), var(--color3), var(--color4), var(--color5));`,
    rule: `margin: -0.5px; clip-path: var(--tri); @random(\${shapeFrequency}) { background: var(--ink); } transition: ease 500ms;`,
  },
  {
    name: 'Crescendo',
    slug: 'crescendo',
    order: 58,
    description:
      'The classic multiplication-table doodle with the numbers stripped away: tone deepens with row times column, while stray accent cells wander on every redraw.',
    palette: ['#FFFFFF', '#60569E', '#E6437D', '#3E8BFF', '#EBBF4D'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    options: [
      { kind: 'grid', default: '8x12' },
      {
        id: 'accents',
        displayName: 'Accents',
        type: 'Slider',
        default: 0.1,
        min: 0,
        max: 0.4,
        step: 0.05,
        replace: '${accentFrequency}',
      },
    ],
    thumb: { grid: '6x6', options: { accents: 0.12 } },
    vars: `--accent: @p(var(--color2), var(--color3), var(--color4));`,
    rule: `margin: 0.5px; background: var(--color1); opacity: @calc(0.04 + 0.96 * sqrt((@x * @y) / (@X * @Y))); @random(\${accentFrequency}) { background: var(--accent); opacity: @rand(0.5, 0.95); } transition: ease 500ms;`,
  },
  {
    name: 'Echo',
    slug: 'echo',
    order: 59,
    description:
      'Concentric squares nested to the center — every ring picks its own color, twist and corner roundness, so each redraw resettles the whole stack.',
    palette: ['#FBF7EF', '#2B1B3D', '#6C4AB6', '#9D7BD8', '#C9AFEF', '#EBDFFA'],
    colors: { min: 2, max: 6, default: 6 },
    options: [
      {
        id: 'rings',
        displayName: 'Rings',
        type: 'Slider',
        default: 7,
        min: 4,
        max: 10,
        step: 1,
        replace: '${rings}',
      },
    ],
    doodle: `:doodle { @grid: 1x\${rings}; @size: \${width} \${height}; overflow:hidden; text-align:center; box-sizing:border-box } :container { background: var(--color0); overflow:hidden; }`,
    thumb: { options: { rings: 6 } },
    vars: ``,
    rule: `@place-cell: center; @size: calc(104% - (@i - 1) * 100% / @I); background: @pd(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5)); border-radius: @rand(2%, 40%); transform: rotate(@rand(-12deg, 12deg)); transition: ease 600ms;`,
  },
  {
    name: 'Circuit',
    slug: 'circuit',
    order: 60,
    description:
      'Random walls of hairline traces with bright component nodes soldered in between — the board rewires itself on every redraw.',
    palette: ['#F7F9F4', '#232529', '#FF3D8B', '#3E8BFF', '#3FFFB2', '#F5DD32'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '10x15',
    freqDefault: 0.6,
    thumb: { grid: '8x8', frequency: 0.6 },
    vars: `--node: @p(var(--color2), var(--color3), var(--color4), var(--color5)); --nx: @rand(18%, 66%); --ny: @rand(18%, 66%);`,
    rule: `margin: -0.5px; @random(\${shapeFrequency}) { border-top: 2px solid var(--color1); } @random(\${shapeFrequency}) { border-left: 2px solid var(--color1); } @random(0.16) { :after { content: ''; position: absolute; @size: 13%; left: var(--nx); top: var(--ny); background: var(--node); transition: ease 500ms; } } transition: ease 500ms;`,
  },
  {
    name: 'Daybreak',
    slug: 'daybreak',
    order: 61,
    description:
      'Rays of light fanning out of the top-left corner — every redraw sweeps the beams to new angles and lengths, like dawn through a window.',
    palette: ['#FCFBFF', '#60569E', '#9B8FD4', '#E6437D', '#3E8BFF', '#C9BFF2'],
    colors: { min: 2, max: 6, default: 6 },
    options: [
      {
        id: 'rays',
        displayName: 'Rays',
        type: 'Slider',
        default: 48,
        min: 24,
        max: 72,
        step: 8,
        replace: '${rays}',
      },
    ],
    doodle: `:doodle { @grid: 1x\${rays}; @size: \${width} \${height}; overflow:hidden; text-align:center; box-sizing:border-box } :container { background: var(--color0); overflow:hidden; }`,
    thumb: { options: { rays: 48 } },
    vars: `--ray: @p(var(--color1), var(--color1), var(--color2), var(--color3), var(--color4), var(--color5));`,
    rule: `@place-cell: 0 0; @size: 200% 1.5px; background: var(--ray); opacity: @rand(0.2, 1); transform: rotate(@rand(1deg, 89deg)) translateX(@rand(-12%, 25%)) scaleX(@rand(0.35, 1)); transition: ease 700ms;`,
  },
  {
    name: 'Shard',
    slug: 'shard',
    order: 62,
    white: true,
    description:
      'Glassy random triangles spun across a dark field — corners stretch and snap to new silhouettes with every seed.',
    palette: ['#1D1F24', '#3EECFF', '#3E8BFF', '#FF3D8B', '#D89FFF', '#3FFFB2'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.9 },
    vars: `--ink: @p(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5));`,
    rule: `@random(\${shapeFrequency}) { background: var(--ink); clip-path: polygon(@rand(0%, 100%) 0%, 100% @rand(0%, 100%), 0% @rand(0%, 100%)); opacity: @rand(0.55, 1); transform: rotate(@rand(360deg)) scale(@rand(0.7, 1.05)); } transition: ease 500ms;`,
  },
  {
    name: 'Cadence',
    slug: 'cadence',
    order: 63,
    description:
      'Rounded bars of random lengths laid out like sheet-music rhythm — on each redraw the whole score breathes to a new measure.',
    palette: ['#FAF6EF', '#232529', '#E6437D', '#3E8BFF', '#3FFFB2', '#F5B82E'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 0.9,
    thumb: { grid: '6x6', frequency: 0.9 },
    vars: `--bar: @p(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5)); --len: @rand(15%, 92%);`,
    rule: `:after { content: ''; position: absolute; left: 4%; top: 33%; height: 34%; width: var(--len); border-radius: 200px; background: var(--bar); opacity: 0; transition: ease 600ms; } @random(\${shapeFrequency}) { :after { opacity: 1; } }`,
  },
  {
    name: 'Flora',
    slug: 'flora',
    order: 64,
    description:
      'A field of clovers, buds and pinwheel blooms — all cut from the same 240-point cloth, so every redraw morphs one flower species into another.',
    palette: ['#FFF6F0', '#FF3D8B', '#D89FFF', '#FF8A5C', '#3FFFB2', '#F5DD32'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.92 },
    vars: `/* clover/bud/hypocycloid all share a 240-point outline, so clip-path interpolates between species */ --bloom: @p(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5)); --species: @p(@shape(clover 3), @shape(clover 5), @shape(bud 4), @shape(bud 6), @shape(hypocycloid 5));`,
    rule: `@random(\${shapeFrequency}) { background: var(--bloom); clip-path: var(--species); transform: rotate(@rand(360deg)) scale(@rand(0.65, 1.08)); } transition: ease 700ms;`,
  },
  {
    name: 'Facet',
    slug: 'facet',
    order: 65,
    description:
      'Diamonds fading out from the center in a manhattan-distance ramp, each one breathing to its own scale on every redraw.',
    palette: ['#191D2E', '#3E8BFF', '#3EECFF', '#D89FFF', '#FF3D8B'],
    colors: { min: 2, max: 5, default: 5 },
    white: true,
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '6x6', frequency: 0.95 },
    vars: `--gem: @p(var(--color1), var(--color1), var(--color2), var(--color3), var(--color4)); --sc: @rand(0.45, 0.85);`,
    rule: `@random(\${shapeFrequency}) { background: var(--gem); opacity: @calc(1 - 0.8 * (abs(@x - (@X + 1) / 2) + abs(@y - (@Y + 1) / 2)) / ((@X + @Y) / 2)); transform: rotate(45deg) scale(var(--sc)); } transition: ease 500ms;`,
  },
  {
    name: 'Wavelet',
    slug: 'wavelet',
    order: 66,
    white: true,
    description:
      'Pearls strung along a serpentine curve — the wave holds its course while every bead swells, glows and dims to the rhythm of the seed.',
    palette: ['#101729', '#97F4FF', '#3EECFF', '#FF3D8B', '#D89FFF'],
    colors: { min: 2, max: 5, default: 5 },
    options: [
      {
        id: 'beads',
        displayName: 'Beads',
        type: 'Slider',
        default: 48,
        min: 24,
        max: 64,
        step: 8,
        replace: '${beads}',
      },
    ],
    doodle: `:doodle { @grid: 1x\${beads}; @size: \${width} \${height}; overflow:hidden; text-align:center; box-sizing:border-box } :container { background: var(--color0); overflow:hidden; }`,
    thumb: { options: { beads: 40 } },
    vars: `--pearl: @p(var(--color1), var(--color1), var(--color2), var(--color3), var(--color4));`,
    rule: `@place-cell: @plot(x: (t-π)/π*.9; y: sin(t*2.5)*.45); @size: calc(@rand(440, 1200) * 1px / @I); border-radius: 50%; background: var(--pearl); opacity: @rand(0.45, 1); transition: ease 700ms;`,
  },
  {
    name: 'Orbit',
    slug: 'orbit',
    order: 67,
    white: true,
    description:
      'Faint orbital rings, each carrying a small bright moon — reseeding sends every moon gliding to a new station along its path.',
    palette: ['#101321', '#97F4FF', '#3EECFF', '#FF3D8B', '#F5DD32', '#3FFFB2'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--moon: @p(var(--color2), var(--color3), var(--color4), var(--color5));`,
    rule: `/* the angle and radius are emitted per cell and shared via @var, so the moon stays on its ring */ --ang: @r(0, 6.2832); --orb: @r(46, 84); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; @size: calc(@var(--orb) * 1%); left: 50%; top: 50%; transform: translate(-50%, -50%); border: calc(14px / @Y) solid var(--color1); border-radius: 50%; opacity: 0.5; transition: ease 700ms; } :after { content: ''; position: absolute; @size: 11%; border-radius: 50%; background: var(--moon); left: calc(50% + cos(@var(--ang) * 1rad) * @var(--orb) * 0.5% - 5.5%); top: calc(50% + sin(@var(--ang) * 1rad) * @var(--orb) * 0.5% - 5.5%); transition: ease 700ms; } }`,
  },
  {
    name: 'Quilt',
    slug: 'quilt',
    order: 68,
    description:
      'Half-square triangle patchwork in fabric tones — each block re-cuts its diagonal and trades patches on every redraw.',
    palette: ['#FBF3E4', '#D96C47', '#E3A92E', '#7FA886', '#2F4156', '#F4E3C8'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.95 },
    vars: `--patch: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --patch2: @p(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5)); --cut: @p(polygon(0% 0%, 100% 0%, 100% 100%), polygon(0% 0%, 100% 0%, 0% 100%), polygon(0% 0%, 100% 100%, 0% 100%), polygon(100% 0%, 100% 100%, 0% 100%));`,
    rule: `@random(\${shapeFrequency}) { width: 94%; height: 94%; margin: 3%; background: var(--patch); :after { content: ''; position: absolute; inset: 0; background: var(--patch2); clip-path: var(--cut); transition: ease 500ms; } } transition: ease 500ms;`,
  },
  {
    name: 'Petal',
    slug: 'petal',
    order: 69,
    description:
      'Single petals pressed across the canvas, each at its own angle, with the odd golden bud between — every redraw sets the petals spinning to rest anew.',
    palette: ['#FFF9F5', '#FF8FB8', '#FFC2D4', '#FF8A5C', '#D89FFF', '#F5C542'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--pet: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --rot: @rand(360deg);`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; inset: 6%; background: var(--pet); clip-path: @shape(drop); transform: rotate(var(--rot)); opacity: 0.92; transition: ease 600ms; } } @random(0.18) { :before { content: ''; position: absolute; @size: 13%; left: 43.5%; top: 43.5%; border-radius: 50%; background: var(--color5); transition: ease 600ms; } }`,
  },
  {
    name: 'Dune',
    slug: 'dune',
    order: 70,
    description:
      'Layered sand mounds rolling along the bottom of every cell — crests rise, fall and lean with each new seed.',
    palette: ['#FFF4DE', '#F4C76F', '#E59A4F', '#C96F3B', '#8C4A32', '#5B334F'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.95 },
    vars: `--sand: @p(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5)); --h: @rand(18%, 96%);`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; left: -2%; right: -2%; bottom: 0; height: var(--h); background: var(--sand); border-radius: @rand(40%, 100%) @rand(40%, 100%) 0 0; opacity: 0.88; transition: ease 700ms; } }`,
  },
  {
    name: 'Lantern',
    slug: 'lantern',
    order: 71,
    white: true,
    description:
      'Paper lanterns drifting in the night, each casting its own halo — reseeding floats them to new heights and re-mixes the glow.',
    palette: ['#181A2E', '#FFD27D', '#FF9E4D', '#FF5E62', '#E84393', '#B388EB'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.85 },
    vars: `--ty: @rand(8%, 38%); --op: @rand(0.55, 1);`,
    rule: `/* lantern body and halo share one emitted color */ --glow: @p(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5)); @random(\${shapeFrequency}) { :after { content: ''; position: absolute; left: 31%; top: var(--ty); width: 38%; height: 50%; border-radius: 30% / 24%; background: @var(--glow); box-shadow: 0 0 calc(300px / @Y) @var(--glow); opacity: var(--op); transition: ease 700ms; } }`,
  },
  {
    name: 'Plasma',
    slug: 'plasma',
    order: 72,
    white: true,
    description:
      'Amoebic blobs wobbling in a petri dish, each with a drifting pale nucleus — the cultures reshape themselves on every redraw.',
    palette: ['#0F2027', '#3FFFB2', '#3EECFF', '#2BB3A3', '#D89FFF', '#E9FFF9'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--blob: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --nx: @rand(28%, 58%); --ny: @rand(28%, 58%);`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; inset: 7%; background: var(--blob); border-radius: @rand(30%, 70%) @rand(30%, 70%) @rand(30%, 70%) @rand(30%, 70%) / @rand(30%, 70%) @rand(30%, 70%) @rand(30%, 70%) @rand(30%, 70%); opacity: 0.85; transition: ease 700ms; } :after { content: ''; position: absolute; @size: 15%; left: var(--nx); top: var(--ny); border-radius: 50%; background: var(--color5); transition: ease 700ms; } }`,
  },
  {
    name: 'Domino',
    slug: 'domino',
    order: 73,
    description:
      'Two-tone tiles flipping between orientations like a table of dominoes mid-shuffle — halves trade colors as the tiles turn.',
    palette: ['#EFEFEA', '#2B4570', '#F6F1E7', '#D34E3A', '#E8B44F', '#4A7C59'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.95 },
    vars: `--a: @p(var(--color1), var(--color2), var(--color3)); --b: @p(var(--color3), var(--color4), var(--color5)); --rot: @p(0deg, 90deg, 180deg, 270deg);`,
    rule: `@random(\${shapeFrequency}) { width: 86%; height: 86%; margin: 7%; background: var(--a); border-radius: 8%; transform: rotate(var(--rot)); :after { content: ''; position: absolute; left: 0; top: 50%; width: 100%; height: 50%; background: var(--b); border-radius: 0 0 10% 10%; transition: ease 500ms; } } transition: ease 500ms;`,
  },
  {
    name: 'Fanfare',
    slug: 'fanfare',
    order: 74,
    description:
      'Hands of color cards fanning open and snapping shut — every redraw deals new colors and a new spread to each fan.',
    palette: ['#F4F2EC', '#E6437D', '#3E8BFF', '#F5B82E', '#3FFFB2', '#8E6BD9'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--c1: @p(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5)); --c2: @p(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5)); --c3: @p(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5));`,
    rule: `/* one emitted spread angle keeps the fan symmetric */ --spread: @r(8, 26); @random(\${shapeFrequency}) { width: 36%; height: 64%; margin: 18% 32%; border-radius: 16% / 10%; background: var(--c2); :before { content: ''; position: absolute; inset: 0; border-radius: 16% / 10%; background: var(--c1); transform: rotate(calc(@var(--spread) * -1deg)); transform-origin: 50% 86%; transition: ease 600ms; } :after { content: ''; position: absolute; inset: 0; border-radius: 16% / 10%; background: var(--c3); transform: rotate(calc(@var(--spread) * 1deg)); transform-origin: 50% 86%; transition: ease 600ms; } } transition: ease 600ms;`,
  },
  {
    name: 'Scallop',
    slug: 'scallop',
    order: 75,
    white: true,
    description:
      'Overlapping mermaid scales in deep-water teals — each scale re-inks itself on redraw, with golden ones glinting through the shoal.',
    palette: ['#0E3A4A', '#1F6E8C', '#2E96B8', '#54C6D8', '#9EEEE0', '#FFD66B'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    options: [
      { kind: 'grid', default: '8x12' },
      {
        id: 'shimmer',
        displayName: 'Shimmer',
        type: 'Slider',
        default: 0.16,
        min: 0,
        max: 0.6,
        step: 0.04,
        replace: '${shimmerFrequency}',
      },
    ],
    thumb: { grid: '6x6', options: { shimmer: 0.16 } },
    vars: `--scale: @p(var(--color1), var(--color2), var(--color3), var(--color4));`,
    rule: `/* upper rows stack above lower ones so each scale's rounded tail shows over the next row */ z-index: calc(@Y - @y + 1); :after { content: ''; position: absolute; left: -8%; right: -8%; top: 0; height: 126%; background: var(--scale); border-radius: 0 0 50% 50% / 0 0 46% 46%; box-shadow: 0 calc(36px / @Y) calc(56px / @Y) rgba(0, 0, 0, 0.18); transition: ease 600ms; } @random(\${shimmerFrequency}) { :after { background: var(--color5); } }`,
  },
  {
    name: 'Ripple',
    slug: 'ripple',
    order: 76,
    white: true,
    description:
      'Rain rings widening over a dark pond — every redraw lands the drops again and sends each pair of ripples growing outward.',
    palette: ['#182D40', '#5BD0F0', '#8FE3FF', '#C2F2FF', '#3E8BFF'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.85 },
    vars: `--d1: @rand(26%, 60%); --d2: @rand(64%, 96%); --o1: @rand(0.5, 1);`,
    rule: `/* both ripples of a drop share one emitted color */ --ring: @p(var(--color1), var(--color2), var(--color3), var(--color4)); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: 50%; top: 50%; transform: translate(-50%, -50%); @size: var(--d1); border: calc(30px / @Y) solid @var(--ring); border-radius: 50%; opacity: var(--o1); transition: ease 700ms; } :after { content: ''; position: absolute; left: 50%; top: 50%; transform: translate(-50%, -50%); @size: var(--d2); border: calc(16px / @Y) solid @var(--ring); border-radius: 50%; opacity: 0.45; transition: ease 700ms; } }`,
  },
  {
    name: 'Pachinko',
    slug: 'pachinko',
    order: 77,
    description:
      'A steady lattice of pegs with bright balls caught mid-fall — each redraw rolls every ball to a new resting spot.',
    palette: ['#FDF6EC', '#232529', '#E6437D', '#3E8BFF', '#F5B82E', '#3FFFB2'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 0.8,
    thumb: { grid: '6x6', frequency: 0.8 },
    vars: `--ball: @p(var(--color2), var(--color3), var(--color4), var(--color5)); --bx: @rand(4%, 70%); --by: @rand(4%, 70%);`,
    rule: `:before { content: ''; position: absolute; @size: 9%; left: 45.5%; top: 45.5%; border-radius: 50%; background: var(--color1); transition: ease 500ms; } @random(\${shapeFrequency}) { :after { content: ''; position: absolute; @size: 26%; left: var(--bx); top: var(--by); border-radius: 50%; background: var(--ball); box-shadow: 0 calc(26px / @Y) calc(34px / @Y) rgba(0, 0, 0, 0.18); transition: ease 700ms; } }`,
  },
  {
    name: 'Ivy',
    slug: 'ivy',
    order: 78,
    description:
      'Quarter-round leaves tiling into winding vines — each leaf swells from a different corner after every redraw, with berries dotted along the way.',
    palette: ['#F2F7EE', '#2F6B3C', '#4F9D5D', '#8CC084', '#C8E6C0', '#E0526E'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '6x6', frequency: 0.95 },
    vars: `--leaf: @p(var(--color1), var(--color1), var(--color2), var(--color3), var(--color4)); --corner: @p(100% 0 0 0, 0 100% 0 0, 0 0 100% 0, 0 0 0 100%);`,
    rule: `@random(\${shapeFrequency}) { width: 96%; height: 96%; margin: 2%; background: var(--leaf); border-radius: var(--corner); } @random(0.12) { :after { content: ''; position: absolute; @size: 18%; left: 41%; top: 41%; border-radius: 50%; background: var(--color5); transition: ease 500ms; } } transition: ease 500ms;`,
  },
  {
    name: 'Portal',
    slug: 'portal',
    order: 79,
    description:
      'Rows of nested doorways rising and sinking from the baseline — every redraw rebuilds the skyline of arches in new heights and hues.',
    palette: ['#F8E9D8', '#C96F3B', '#8C4A6B', '#5B3A6E', '#E8A04C'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.95 },
    vars: `--arch1: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --arch2: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --h1: @rand(55%, 94%); --h2: @rand(24%, 48%);`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: 16%; bottom: 0; width: 68%; height: var(--h1); background: var(--arch1); border-radius: 999px 999px 0 0; transition: ease 600ms; } :after { content: ''; position: absolute; left: 31%; bottom: 0; width: 38%; height: var(--h2); background: var(--arch2); border-radius: 999px 999px 0 0; transition: ease 600ms; } }`,
  },
  {
    name: 'Neon',
    slug: 'neon',
    order: 80,
    white: true,
    description:
      'Glowing tube segments rearranging themselves on a dark wall — each redraw re-aims the lights and re-mixes their halos.',
    palette: ['#14101F', '#FF2E97', '#2EE6FF', '#B14EFF', '#45FFA2'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.8,
    thumb: { grid: '5x5', frequency: 0.8 },
    vars: `--ang: @p(0deg, 45deg, 90deg, 135deg);`,
    rule: `/* tube and both halos share one emitted color */ --tube: @p(var(--color1), var(--color2), var(--color3), var(--color4)); @random(\${shapeFrequency}) { transform: rotate(var(--ang)); :after { content: ''; position: absolute; left: 14%; top: 47%; width: 72%; height: 6%; border-radius: 99px; background: @var(--tube); box-shadow: 0 0 calc(80px / @Y) @var(--tube), 0 0 calc(200px / @Y) @var(--tube); transition: ease 500ms; } } transition: ease 500ms;`,
  },
  {
    name: 'Bokeh',
    slug: 'bokeh',
    order: 81,
    white: true,
    description:
      'Out-of-focus city lights swimming in the dark — discs drift, swell and refocus softly with every redraw.',
    palette: ['#1A1626', '#FFC15E', '#FF8FA3', '#8AB6FF', '#C490FF', '#FFE9B8'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.85 },
    vars: `--light: @p(var(--color1), var(--color2), var(--color3), var(--color4), var(--color5)); --d: @rand(26%, 88%); --lx: @rand(-10%, 60%); --ly: @rand(-10%, 60%); --lo: @rand(0.25, 0.9); --bl: @rand(1px, 6px);`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; @size: var(--d); left: var(--lx); top: var(--ly); border-radius: 50%; background: var(--light); opacity: var(--lo); filter: blur(var(--bl)); transition: ease 800ms; } }`,
  },
  {
    name: 'Gauge',
    slug: 'gauge',
    order: 82,
    description:
      'A wall of instrument dials — on every redraw the needles swing to fresh readings with a springy overshoot.',
    palette: ['#F4F4F0', '#C9CDC4', '#232529', '#E6437D', '#3E8BFF'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.95 },
    vars: `--sweep: @rand(-120deg, 120deg); --dial: @p(var(--color1), var(--color2)); --pin: @p(var(--color3), var(--color4));`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; inset: 12%; border-radius: 50%; border: calc(36px / @Y) solid var(--dial); opacity: 0.9; transition: ease 600ms; } :after { content: ''; position: absolute; left: 47.75%; bottom: 50%; width: 4.5%; height: 31%; border-radius: 99px; background: var(--pin); transform: rotate(var(--sweep)); transform-origin: 50% 100%; transition: cubic-bezier(0.34, 1.56, 0.64, 1) 700ms; } }`,
  },
  {
    name: 'Drift',
    slug: 'drift',
    order: 83,
    white: true,
    description:
      'Pairs of spores floating through still water, the small one trailing its leader — each redraw carries every pair somewhere new.',
    palette: ['#0F1B17', '#9EFFD8', '#5ED9A0', '#CFFFE8', '#F5DD32'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 0.9,
    thumb: { grid: '6x6', frequency: 0.85 },
    vars: `--s1: @rand(11%, 26%); --s2: @rand(6%, 15%); --x1: @rand(5%, 70%); --y1: @rand(5%, 70%); --x2: @rand(10%, 78%); --y2: @rand(10%, 78%);`,
    rule: `/* leader and follower share one emitted color */ --mote: @p(var(--color1), var(--color2), var(--color3), var(--color4)); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; @size: var(--s1); left: var(--x1); top: var(--y1); border-radius: 50%; background: @var(--mote); opacity: 0.9; transition: ease 800ms; } :after { content: ''; position: absolute; @size: var(--s2); left: var(--x2); top: var(--y2); border-radius: 50%; background: @var(--mote); opacity: 0.4; transition: ease 800ms; } }`,
  },
  {
    name: 'Sash',
    slug: 'sash',
    order: 84,
    white: true,
    description:
      'Translucent silk ribbons laid diagonally across the dark — they slide, widen and flip their slant with every redraw.',
    palette: ['#2A1E3F', '#FF6FB5', '#FFA94D', '#845EF7', '#4DD4FF'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--silk: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --sy: @rand(8%, 66%); --sh: @rand(10%, 34%); --tilt: @p(-45deg, 45deg);`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; left: -30%; width: 160%; top: var(--sy); height: var(--sh); background: var(--silk); transform: rotate(var(--tilt)); opacity: 0.8; border-radius: 99px; transition: ease 600ms; } }`,
  },
  {
    name: 'Kite',
    slug: 'kite',
    order: 85,
    description:
      'A sky of paper kites warping in the wind, tails streaming behind — every redraw bends each diamond and tips it to a new angle.',
    palette: ['#DCF0FF', '#FF5E78', '#FFB13D', '#7A5CF0', '#2BB3A3', '#2F4156'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--sail: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --tilt: @rand(-24deg, 24deg);`,
    rule: `/* spine and crossbar positions are emitted once and shared by the sail outline and the tail */ --kx: @r(38, 62); --ky: @r(22, 44); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; inset: 6%; background: var(--sail); clip-path: polygon(calc(@var(--kx) * 1%) 0%, @rand(72%, 100%) calc(@var(--ky) * 1%), calc(@var(--kx) * 1%) @rand(78%, 100%), @rand(0%, 28%) calc(@var(--ky) * 1%)); transform: rotate(var(--tilt)); transition: ease 600ms; } :after { content: ''; position: absolute; @size: 6%; left: calc(@var(--kx) * 1% - 3%); top: 88%; border-radius: 50%; background: var(--color5); box-shadow: calc(-40px / @Y) calc(30px / @Y) 0 var(--color5); transition: ease 600ms; } }`,
  },
  {
    name: 'Pendulum',
    slug: 'pendulum',
    order: 86,
    description:
      'Bobs hanging from slender rods, caught mid-swing — every redraw releases them to sway springily to new angles.',
    palette: ['#F6F4EF', '#232529', '#E6437D', '#3E8BFF', '#F5B82E', '#2BB3A3'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.95 },
    vars: `--bob: @p(var(--color2), var(--color3), var(--color4), var(--color5));`,
    rule: `/* rod and bob share one emitted swing angle and a common pivot, so the pendulum stays rigid */ --swing: @r(-30, 30); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: 49.4%; top: 6%; width: 1.2%; height: 42%; border-radius: 99px; background: var(--color1); opacity: 0.7; transform: rotate(calc(@var(--swing) * 1deg)); transform-origin: 50% 0%; transition: cubic-bezier(0.3, 1.4, 0.6, 1) 800ms; } :after { content: ''; position: absolute; @size: 16%; left: 42%; top: 48%; border-radius: 50%; background: var(--bob); transform: rotate(calc(@var(--swing) * 1deg)); transform-origin: 50% -262.5%; transition: cubic-bezier(0.3, 1.4, 0.6, 1) 800ms; } }`,
  },
  {
    name: 'Atom',
    slug: 'atom',
    order: 87,
    white: true,
    description:
      'Electron shells whirling around golden nuclei — both orbits spin to new inclinations on every redraw.',
    palette: ['#101720', '#FFE066', '#58E6D9', '#7FA3FF', '#FF7AA8', '#DDE7F5'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--spin1: @rand(360deg); --spin2: @rand(360deg); --orb: @p(var(--color2), var(--color3), var(--color4));`,
    rule: `@random(\${shapeFrequency}) { background: radial-gradient(circle, var(--color1) 0 5%, transparent 5.5%); :before { content: ''; position: absolute; left: 14%; top: 33%; width: 72%; height: 34%; border: calc(20px / @Y) solid var(--orb); border-radius: 50%; transform: rotate(var(--spin1)); transition: ease 700ms; } :after { content: ''; position: absolute; left: 14%; top: 33%; width: 72%; height: 34%; border: calc(20px / @Y) solid var(--color5); border-radius: 50%; transform: rotate(var(--spin2)); opacity: 0.7; transition: ease 700ms; } }`,
  },
  {
    name: 'Shuffle',
    slug: 'shuffle',
    order: 88,
    description:
      'Pairs of rounded blocks sliding between the four corners of their frame — every redraw deals a new arrangement, like tiles in a pocket puzzle.',
    palette: ['#FFF8E8', '#FF6B6B', '#4ECDC4', '#FFD93D', '#6C5CE7', '#95E1D3'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.9 },
    vars: `--q1x: @p(2%, 52%); --q1y: @p(2%, 52%); --q2x: @p(2%, 52%); --q2y: @p(2%, 52%); --blk1: @p(var(--color1), var(--color2), var(--color3)); --blk2: @p(var(--color3), var(--color4), var(--color5));`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; @size: 46%; left: var(--q1x); top: var(--q1y); border-radius: 14%; background: var(--blk1); transition: ease 500ms; } :after { content: ''; position: absolute; @size: 46%; left: var(--q2x); top: var(--q2y); border-radius: 14%; background: var(--blk2); opacity: 0.92; transition: ease 500ms; } }`,
  },
  {
    name: 'Monsoon',
    slug: 'monsoon',
    order: 89,
    white: true,
    description:
      'Raindrops caught at different moments of their fall, with splash rings blooming below — every redraw advances the storm by one beat.',
    palette: ['#20303C', '#6FC3DF', '#9FDCF0', '#C9EEF7', '#DFF6FC'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 0.9,
    thumb: { grid: '6x6', frequency: 0.85 },
    vars: `--rain: @p(var(--color1), var(--color2), var(--color3)); --dx: @rand(12%, 74%); --dy: @rand(0%, 56%); --so: @rand(0.3, 0.9);`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: var(--dx); top: var(--dy); width: 14%; height: 30%; background: var(--rain); clip-path: @shape(drop); transform: rotate(180deg); transition: ease 600ms; } } @random(0.2) { :after { content: ''; position: absolute; left: 30%; bottom: 5%; width: 40%; height: 11%; border: calc(14px / @Y) solid var(--color4); border-radius: 50%; opacity: var(--so); transition: ease 600ms; } }`,
  },
  {
    name: 'Hive',
    slug: 'hive',
    order: 90,
    description:
      'Honeycomb chips in amber and gold — each hexagon pulses to its own size and twist whenever the seed changes.',
    palette: ['#FFF4D6', '#F5B82E', '#E8920C', '#C96F1F', '#8C5A2B', '#E6437D'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.92 },
    vars: `--honey: @p(var(--color1), var(--color1), var(--color2), var(--color3), var(--color4), var(--color5)); --hs: @rand(0.55, 0.98); --hr: @p(0deg, 30deg, 90deg);`,
    rule: `@random(\${shapeFrequency}) { background: var(--honey); clip-path: @shape(hexagon); transform: scale(var(--hs)) rotate(var(--hr)); } transition: ease 500ms;`,
  },
  {
    name: 'Aster',
    slug: 'aster',
    order: 91,
    description:
      'Six-armed thread stars twirling lazily across the canvas — every redraw spins each one to a new resting angle.',
    palette: ['#FFF8F2', '#FF7E9D', '#FFB35C', '#9D89F2', '#54C6B8'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 0.9,
    thumb: { grid: '5x5', frequency: 0.9 },
    vars: `--spin: @rand(180deg);`,
    rule: `/* all three arms share one emitted color */ --star: @p(var(--color1), var(--color2), var(--color3), var(--color4)); @random(\${shapeFrequency}) { width: 72%; height: 2.6%; margin: 48.7% 14%; border-radius: 99px; background: @var(--star); transform: rotate(var(--spin)); :before { content: ''; position: absolute; inset: 0; border-radius: 99px; background: @var(--star); transform: rotate(60deg); } :after { content: ''; position: absolute; inset: 0; border-radius: 99px; background: @var(--star); transform: rotate(120deg); } } transition: ease 600ms;`,
  },
  {
    name: 'Fizz',
    slug: 'fizz',
    order: 92,
    description:
      'Champagne bubbles — hollow rings and bright sparks — drifting through amber, finding new positions with every pour of the seed.',
    palette: ['#F9E8C9', '#E8B04B', '#D88A2B', '#B86A1F', '#FFF6E3'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 0.9,
    thumb: { grid: '6x6', frequency: 0.9 },
    vars: `--bub: @p(var(--color1), var(--color2), var(--color3)); --b1: @rand(20%, 46%); --b2: @rand(8%, 18%); --fx1: @rand(6%, 60%); --fy1: @rand(4%, 70%); --fx2: @rand(12%, 78%); --fy2: @rand(8%, 80%);`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; @size: var(--b1); left: var(--fx1); top: var(--fy1); border: calc(26px / @Y) solid var(--bub); border-radius: 50%; opacity: 0.85; transition: ease 700ms; } :after { content: ''; position: absolute; @size: var(--b2); left: var(--fx2); top: var(--fy2); border-radius: 50%; background: var(--color4); opacity: 0.6; transition: ease 700ms; } }`,
  },
  {
    name: 'Wink',
    slug: 'wink',
    order: 93,
    white: true,
    description:
      'A wall of almond eyes blinking out of the dark — lids open and close to new degrees on every redraw, irises following.',
    palette: ['#2B2435', '#FFF4E8', '#54C6B8', '#F5B82E', '#E6437D', '#B388EB'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.95 },
    vars: `--iris: @p(var(--color2), var(--color3), var(--color4), var(--color5));`,
    rule: `/* one emitted lid height drives lens and iris together, so the eye squints as one */ --lid: @r(8, 36); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: 13%; top: calc(50% - @var(--lid) * 1%); width: 74%; height: calc(@var(--lid) * 2%); background: var(--color1); border-radius: 50%; transition: ease 500ms; } :after { content: ''; position: absolute; left: calc(50% - @var(--lid) * 0.55%); top: calc(50% - @var(--lid) * 0.55%); width: calc(@var(--lid) * 1.1%); height: calc(@var(--lid) * 1.1%); background: var(--iris); border-radius: 50%; transition: ease 500ms; } }`,
  },
  {
    name: 'Stamp',
    slug: 'stamp',
    order: 94,
    description:
      'A sheet of postage stamps, each perforated edge punched by the background — stamps tilt and re-ink their centers with every redraw.',
    palette: ['#F4EFE6', '#FFFFFF', '#E6437D', '#3E8BFF', '#2BB3A3', '#F5B82E'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.95 },
    vars: `--mark: @p(var(--color2), var(--color3), var(--color4), var(--color5)); --tilt: @rand(-7deg, 7deg);`,
    rule: `@random(\${shapeFrequency}) { width: 80%; height: 80%; margin: 10%; background: var(--color1); border: calc(22px / @Y) dotted var(--color0); box-shadow: 0 calc(10px / @Y) calc(40px / @Y) rgba(0, 0, 0, 0.16); transform: rotate(var(--tilt)); :after { content: ''; position: absolute; inset: 16%; background: var(--mark); border-radius: 10%; transition: ease 500ms; } } transition: ease 500ms;`,
  },
  {
    name: 'Ridge',
    slug: 'ridge',
    order: 95,
    description:
      'Mountain silhouettes at dusk, suns hanging low between the peaks — each redraw slides every summit and re-hangs the light.',
    palette: ['#FFE3D8', '#6E4A7E', '#91608F', '#B7789B', '#4A3859', '#FFB13D'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.95 },
    vars: `--rock: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --apex: @rand(20%, 80%); --rise: @rand(4%, 56%); --sunx: @rand(18%, 68%);`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; left: -6%; right: -6%; top: 0; bottom: 0; background: var(--rock); clip-path: polygon(var(--apex) var(--rise), 112% 100%, -12% 100%); opacity: 0.85; transition: ease 700ms; } } @random(0.12) { :before { content: ''; position: absolute; @size: 16%; left: var(--sunx); top: 10%; border-radius: 50%; background: var(--color5); transition: ease 700ms; } }`,
  },
  {
    name: 'Madras',
    slug: 'madras',
    order: 96,
    description:
      'Translucent bands crossing warp and weft, patchworked cell by cell — the whole cloth re-weaves itself on every redraw.',
    palette: ['#FFF9EE', '#E2543E', '#2E86AB', '#F5B82E', '#4F9D5D'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.95 },
    vars: `--warp: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --weft: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --wx: @rand(0%, 55%); --ww: @rand(22%, 60%); --wy: @rand(0%, 55%); --wh: @rand(22%, 60%);`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; top: -1%; bottom: -1%; left: var(--wx); width: var(--ww); background: var(--warp); opacity: 0.55; transition: ease 600ms; } :after { content: ''; position: absolute; left: -1%; right: -1%; top: var(--wy); height: var(--wh); background: var(--weft); opacity: 0.55; transition: ease 600ms; } }`,
  },
];
