// Batch 2 (gallery orders 97-136).

export const batch2 = [
  {
    name: 'Crux',
    slug: 'crux',
    order: 97,
    description:
      'Both diagonals of the grid picked out in morphing tiles, with stray dots scattered off-axis — a study of the @match selector.',
    palette: ['#F6F6F2', '#232529', '#E6437D', '#3E8BFF', '#F5B82E'],
    colors: { min: 2, max: 5, default: 5 },
    options: [
      { kind: 'grid', default: '8x12' },
      {
        id: 'speckle',
        displayName: 'Speckle',
        type: 'Slider',
        default: 0.1,
        min: 0,
        max: 0.4,
        step: 0.05,
        replace: '${speckleFrequency}',
      },
    ],
    thumb: { grid: '7x7', options: { speckle: 0.1 } },
    vars: ``,
    rule: `--ink: @p(var(--color1), var(--color1), var(--color2), var(--color3)); --br: @p(0%, 14%, 50%); --sc: @r(0.6, 1); margin: 1px; transition: ease 500ms; @match(x == y) { background: @var(--ink); border-radius: @var(--br); transform: scale(@var(--sc)); } @match(X - x + 1 == y) { background: @var(--ink); border-radius: @var(--br); transform: scale(@var(--sc)); } @random(\${speckleFrequency}) { background: var(--color4); border-radius: 50%; transform: scale(0.35); }`,
  },
  {
    name: 'Checker',
    slug: 'checker',
    order: 98,
    description:
      'A classic checkerboard whose light squares host discs that swell and shrink — the dark squares hold the grid steady while the pieces breathe.',
    palette: ['#F7EFDD', '#2F4156', '#E6437D', '#F5B82E', '#3E8BFF', '#2BB3A3'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    options: [
      { kind: 'grid', default: '8x12' },
      {
        id: 'discSize',
        displayName: 'Disc size',
        type: 'Slider',
        default: 70,
        min: 40,
        max: 85,
        step: 5,
        replace: '${discSize}',
      },
    ],
    thumb: { grid: '6x6', options: { discSize: 70 } },
    vars: `--disc: @p(var(--color2), var(--color3), var(--color4), var(--color5));`,
    rule: `--ds: @r(18, ${'${discSize}'}); transition: ease 500ms; @match((x + y) % 2 == 0) { background: var(--color1); } @match((x + y) % 2 == 1) { :after { content: ''; position: absolute; @size: calc(@var(--ds) * 1%); left: calc(50% - @var(--ds) * 0.5%); top: calc(50% - @var(--ds) * 0.5%); border-radius: 50%; background: var(--disc); transition: ease 500ms; } }`,
  },
  {
    name: 'Tremor',
    slug: 'tremor',
    order: 99,
    description:
      'A continuous baseline running through every cell, pulsing with mostly-small beats and the occasional sharp spike — a seismograph of the seed.',
    palette: ['#FBFAF7', '#232529', '#E03131', '#3E8BFF', '#B9B5AC'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '10x15',
    freqDefault: 0.9,
    thumb: { grid: '7x7', frequency: 0.9 },
    vars: `--pulse: @p(var(--color1), var(--color1), var(--color1), var(--color2), var(--color3));`,
    rule: `--tw: @r(4, 9); --th: @p(@r(10, 30), @r(12, 36), @r(48, 94)); :before { content: ''; position: absolute; left: -2%; right: -2%; top: 49.4%; height: 1.2%; background: var(--color4); opacity: 0.5; transition: ease 500ms; } @random(\${shapeFrequency}) { :after { content: ''; position: absolute; left: calc(50% - @var(--tw) * 0.5%); top: calc(50% - @var(--th) * 0.5%); width: calc(@var(--tw) * 1%); height: calc(@var(--th) * 1%); border-radius: 99px; background: var(--pulse); transition: ease 500ms; } }`,
  },
  {
    name: 'Jelly',
    slug: 'jelly',
    order: 100,
    description:
      'Glossy candy blobs squashing and stretching like jelly, each with a sliding highlight — every redraw gives the tray a wobble.',
    palette: ['#FFF0F4', '#FF6FA5', '#FF9F68', '#9D89F2', '#4FD8C4'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.92 },
    vars: `--goo: @p(var(--color1), var(--color2), var(--color3), var(--color4));`,
    rule: `/* the highlight derives from the same emitted geometry as its blob, so it stays glued on */ --jx: @r(5, 28); --jy: @r(5, 28); --jw: @r(42, 66); --jh: @r(42, 66); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: calc(@var(--jx) * 1%); top: calc(@var(--jy) * 1%); width: calc(@var(--jw) * 1%); height: calc(@var(--jh) * 1%); background: var(--goo); border-radius: 50%; transition: ease 700ms; } :after { content: ''; position: absolute; left: calc((@var(--jx) + @var(--jw) * 0.18) * 1%); top: calc((@var(--jy) + @var(--jh) * 0.13) * 1%); width: calc(@var(--jw) * 0.24%); height: calc(@var(--jh) * 0.18%); background: rgba(255, 255, 255, 0.85); border-radius: 50%; transition: ease 700ms; } }`,
  },
  {
    name: 'Bunting',
    slug: 'bunting',
    order: 101,
    description:
      'Strings of party pennants swaying from their lines — every redraw recolors the flags and sends a breeze through them.',
    palette: ['#FDF8EE', '#E6437D', '#3E8BFF', '#F5B82E', '#2BB3A3', '#8A8273'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '5x5', frequency: 0.9 },
    vars: `--flag: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --sway: @rand(-14deg, 14deg);`,
    rule: `:before { content: ''; position: absolute; left: -2%; right: -2%; top: 6%; height: 1.4%; background: var(--color5); opacity: 0.7; transition: ease 500ms; } @random(\${shapeFrequency}) { :after { content: ''; position: absolute; left: 27%; top: 7%; width: 46%; height: 60%; background: var(--flag); clip-path: polygon(0% 0%, 100% 0%, 50% 100%); transform: rotate(var(--sway)); transform-origin: 50% 0%; transition: ease 700ms; } }`,
  },
  {
    name: 'Koi',
    slug: 'koi',
    order: 102,
    description:
      'A pond of koi that sometimes dream of being whales — the 240-point outlines morph between species as the fish turn with each redraw.',
    palette: ['#DFF2F0', '#FF7E5A', '#FF4D6D', '#FFB13D', '#FFFFFF', '#2F4156'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--fish: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --swim: @p(@shape(fish), @shape(fish), @shape(whale)); --dir: @rand(-28deg, 28deg); --flip: @p(1, -1);`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; inset: @rand(4%, 16%); background: var(--fish); clip-path: var(--swim); transform: rotate(var(--dir)) scaleX(var(--flip)); opacity: 0.92; transition: ease 800ms; } } @random(0.14) { :before { content: ''; position: absolute; @size: 8%; left: @rand(10%, 80%); top: @rand(10%, 80%); border-radius: 50%; border: 1.5px solid var(--color5); opacity: 0.5; transition: ease 800ms; } }`,
  },
  {
    name: 'Valentine',
    slug: 'valentine',
    order: 103,
    description:
      'Hearts that melt into drops and beans and back again — every redraw lets each sweet pick a new shape, tilt and blush.',
    palette: ['#FFF5F6', '#FF4D6D', '#FF8FA3', '#C9184A', '#FFB3C1'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.92 },
    vars: `--sweet: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --form: @p(@shape(heart), @shape(heart), @shape(drop), @shape(bean)); --tilt: @rand(-20deg, 20deg); --pump: @rand(0.7, 1.05);`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; inset: 8%; background: var(--sweet); clip-path: var(--form); transform: rotate(var(--tilt)) scale(var(--pump)); transition: ease 700ms; } }`,
  },
  {
    name: 'Seastar',
    slug: 'seastar',
    order: 104,
    description:
      'Plump starfish sunning on the sand, pebbles scattered between — each redraw rolls every star to a new angle and size.',
    palette: ['#FCEFD8', '#FF8A5C', '#E96D4F', '#D94F30', '#B7A98F'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--star: @p(var(--color1), var(--color2), var(--color3)); --gap: @rand(6%, 22%); --px: @rand(10%, 82%); --py: @rand(10%, 82%);`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; inset: var(--gap); background: var(--star); clip-path: @shape(star); transform: rotate(@rand(360deg)); transition: ease 800ms; } } @random(0.2) { :before { content: ''; position: absolute; @size: 8%; left: var(--px); top: var(--py); border-radius: 50%; background: var(--color4); transition: ease 800ms; } }`,
  },
  {
    name: 'Aperture',
    slug: 'aperture',
    order: 105,
    white: true,
    description:
      'Camera irises dilating and stopping down across a dark contact sheet — ring thickness morphs between seeds like light being let in.',
    palette: ['#15171C', '#E8E6E1', '#F5B82E', '#3EECFF', '#FF3D8B'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.92 },
    vars: `--iris: @p(var(--color1), var(--color1), var(--color2), var(--color3), var(--color4));`,
    rule: `/* the aperture is a disc with a punched hole; the hole size morphs so the iris dilates */ @random(\${shapeFrequency}) { :before { content: ''; position: absolute; inset: 9%; border-radius: 50%; background: var(--iris); transition: ease 700ms; } :after { content: ''; position: absolute; inset: @rand(16%, 44%); border-radius: 50%; background: var(--color0); transition: ease 700ms; } }`,
  },
  {
    name: 'Posy',
    slug: 'posy',
    order: 106,
    description:
      'Six-petaled posies built from orbiting dots around a golden core — bouquets spin and re-bloom on every redraw.',
    palette: ['#F3F7EC', '#E6437D', '#9D5BD2', '#FF8A5C', '#F5C542'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--bloomSpin: @rand(60deg);`,
    rule: `/* petals are box-shadow copies of the core at hexagon offsets around one emitted radius, so the bloom opens as a unit */ --pet: @p(var(--color1), var(--color2), var(--color3)); --pr: @r(15, 26); --pw: @r(14, 22); @random(\${shapeFrequency}) { :after { content: ''; position: absolute; @size: calc(@var(--pw) * 1%); left: calc(50% - @var(--pw) * 0.5%); top: calc(50% - @var(--pw) * 0.5%); border-radius: 50%; background: var(--color4); box-shadow: 0 calc(@var(--pr) * -10px / @Y) 0 @var(--pet), calc(@var(--pr) * 8.66px / @Y) calc(@var(--pr) * -5px / @Y) 0 @var(--pet), calc(@var(--pr) * 8.66px / @Y) calc(@var(--pr) * 5px / @Y) 0 @var(--pet), 0 calc(@var(--pr) * 10px / @Y) 0 @var(--pet), calc(@var(--pr) * -8.66px / @Y) calc(@var(--pr) * 5px / @Y) 0 @var(--pet), calc(@var(--pr) * -8.66px / @Y) calc(@var(--pr) * -5px / @Y) 0 @var(--pet); transform: rotate(var(--bloomSpin)); transition: ease 700ms; } }`,
  },
  {
    name: 'Dapple',
    slug: 'dapple',
    order: 107,
    description:
      'Big watercolor washes layered wet-on-wet — translucent discs drift and overlap into new pools of color with every redraw.',
    palette: ['#FFFFFF', '#3E8BFF', '#E6437D', '#F5B82E', '#2BB3A3'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--wash1: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --wash2: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --w1: @rand(60%, 130%); --w2: @rand(40%, 100%); --wx1: @rand(-30%, 50%); --wy1: @rand(-30%, 50%); --wx2: @rand(-20%, 60%); --wy2: @rand(-20%, 60%);`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; @size: var(--w1); left: var(--wx1); top: var(--wy1); border-radius: 50%; background: var(--wash1); opacity: 0.3; transition: ease 800ms; } :after { content: ''; position: absolute; @size: var(--w2); left: var(--wx2); top: var(--wy2); border-radius: 50%; background: var(--wash2); opacity: 0.3; transition: ease 800ms; } }`,
  },
  {
    name: 'Vane',
    slug: 'vane',
    order: 108,
    description:
      'A field of weather vanes snapping to new headings — darts swing round with a springy overshoot whenever the wind (seed) shifts.',
    palette: ['#EEF2EE', '#1F3A33', '#D94F30', '#3E8BFF', '#F5B82E'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.92 },
    vars: `--head: @p(0deg, 45deg, 90deg, 135deg, 180deg, 225deg, 270deg, 315deg); --ink: @p(var(--color1), var(--color1), var(--color2), var(--color3), var(--color4));`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; inset: 14%; background: var(--ink); clip-path: polygon(50% 0%, 88% 100%, 50% 72%, 12% 100%); transform: rotate(var(--head)); transition: cubic-bezier(0.34, 1.4, 0.64, 1) 700ms; } }`,
  },
  {
    name: 'Argyle',
    slug: 'argyle',
    order: 109,
    description:
      'A lattice of lozenges whose vertices quiver from seed to seed, dotted with pale pips — knitwear that never sits still.',
    palette: ['#F4EFE4', '#7A1F3D', '#2F4156', '#C9A86A', '#EFE8D8'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.95 },
    vars: `--lozenge: @p(var(--color1), var(--color2), var(--color3));`,
    rule: `/* each vertex jitters independently, so the lozenges quiver organically */ @random(\${shapeFrequency}) { background: var(--lozenge); clip-path: polygon(50% @rand(-6%, 10%), calc(100% - @rand(-6%, 10%)) 50%, 50% calc(100% - @rand(-6%, 10%)), @rand(-6%, 10%) 50%); } @random(0.22) { :after { content: ''; position: absolute; @size: 13%; left: 43.5%; top: 43.5%; border-radius: 50%; background: var(--color4); transition: ease 600ms; } } transition: ease 600ms;`,
  },
  {
    name: 'Strata',
    slug: 'strata',
    order: 110,
    description:
      'Bands of sediment drifting through the rock — thick seams and hairline veins settle into new layers on every redraw.',
    palette: ['#F7F1E5', '#C96F3B', '#8C5A3B', '#5B4232', '#D9A05B', '#2E2620'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.95 },
    vars: `--sed: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --s1y: @rand(8%, 78%); --s1h: @p(@rand(4%, 9%), @rand(12%, 26%)); --s2y: @rand(10%, 85%);`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: -2%; right: -2%; top: var(--s1y); height: var(--s1h); background: var(--sed); opacity: 0.85; border-radius: 99px; transition: ease 700ms; } } @random(0.55) { :after { content: ''; position: absolute; left: -2%; right: -2%; top: var(--s2y); height: 2.5%; background: var(--color5); opacity: 0.55; border-radius: 99px; transition: ease 700ms; } }`,
  },
  {
    name: 'Buoy',
    slug: 'buoy',
    order: 111,
    description:
      'Bright floats bobbing on a steady waterline — every redraw lifts and settles them to new heights on the swell.',
    palette: ['#E8F6FA', '#2E86AB', '#E2543E', '#F5B82E', '#2F4156'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 0.8,
    thumb: { grid: '5x5', frequency: 0.8 },
    vars: `--float: @p(var(--color2), var(--color3), var(--color4)); --lift: @rand(-6%, 10%);`,
    rule: `--bd: @r(24, 46); :before { content: ''; position: absolute; left: -2%; right: -2%; top: 62%; height: 2%; border-radius: 99px; background: var(--color1); opacity: 0.6; transition: ease 600ms; } @random(\${shapeFrequency}) { :after { content: ''; position: absolute; @size: calc(@var(--bd) * 1%); left: calc(50% - @var(--bd) * 0.5%); top: calc(63% - @var(--bd) * 0.5% - var(--lift)); border-radius: 50%; background: var(--float); transition: ease 600ms; } }`,
  },
  {
    name: 'Kelp',
    slug: 'kelp',
    order: 112,
    white: true,
    description:
      'A kelp forest swaying in the current — strands grow, shrink and lean together whenever the tide (seed) turns.',
    palette: ['#0B2E33', '#2E7D6B', '#4CAF8E', '#7BD8B0', '#A8E6CF'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.95 },
    vars: `--frond1: @p(var(--color1), var(--color2), var(--color3)); --frond2: @p(var(--color2), var(--color3), var(--color4)); --k1: @rand(40%, 96%); --k2: @rand(30%, 80%); --sway1: @rand(-22deg, 22deg); --sway2: @rand(-22deg, 22deg);`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: 30%; bottom: 0; width: 9%; height: var(--k1); border-radius: 99px; background: var(--frond1); transform: skewX(var(--sway1)); transform-origin: 50% 100%; transition: ease 800ms; } :after { content: ''; position: absolute; left: 58%; bottom: 0; width: 9%; height: var(--k2); border-radius: 99px; background: var(--frond2); transform: skewX(var(--sway2)); transform-origin: 50% 100%; transition: ease 800ms; } }`,
  },
  {
    name: 'Drip',
    slug: 'drip',
    order: 113,
    description:
      'Fresh paint running down the wall — streams lengthen and droplets let go a little further on every redraw.',
    palette: ['#FAFAF7', '#E6437D', '#3E8BFF', '#F5B82E', '#16C79A'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '5x5', frequency: 0.9 },
    vars: `--dropOp: @p(0, 1, 1);`,
    rule: `/* the droplet hangs from the same emitted stream geometry and shares its color */ --paint: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --dpx: @r(14, 62); --dpw: @r(12, 26); --dph: @r(20, 82); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: calc(@var(--dpx) * 1%); top: -2%; width: calc(@var(--dpw) * 1%); height: calc(@var(--dph) * 1%); background: @var(--paint); border-radius: 0 0 99px 99px; transition: ease 800ms; } :after { content: ''; position: absolute; left: calc((@var(--dpx) + @var(--dpw) / 2) * 1% - 4%); top: calc(@var(--dph) * 1% + 4%); @size: 8%; background: @var(--paint); border-radius: 50%; opacity: var(--dropOp); transition: ease 800ms; } }`,
  },
  {
    name: 'Bauhaus',
    slug: 'bauhaus',
    order: 114,
    description:
      'Circles, half-rounds, leaves and squares all cut from one border-radius — so every form morphs fluidly into the next on each redraw.',
    palette: ['#F2E9DC', '#E63329', '#1D3D8F', '#F0C02E', '#1A1A1A'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.95 },
    vars: `/* every primitive is just a border-radius, so all of them interpolate */ --form: @p('50% 50% 50% 50%', '100% 100% 0% 0%', '0% 0% 100% 100%', '100% 0% 0% 100%', '0% 100% 100% 0%', '0% 0% 0% 0%', '100% 0% 100% 0%', '0% 100% 0% 100%'); --bold: @p(var(--color1), var(--color2), var(--color3), var(--color4));`,
    rule: `@random(\${shapeFrequency}) { background: var(--bold); border-radius: var(--form); } transition: ease 600ms;`,
  },
  {
    name: 'Cairn',
    slug: 'cairn',
    order: 115,
    description:
      'Little balanced stone stacks — each redraw nudges every stone, and somehow the cairns always settle again.',
    palette: ['#F1EFEA', '#8D99A6', '#5C6B73', '#3C4A52', '#B8C2CA'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--stone1: @p(var(--color1), var(--color2), var(--color3)); --stone2: @p(var(--color2), var(--color3), var(--color4)); --c2h: @rand(14%, 24%);`,
    rule: `/* the top stone rests on the emitted height of the bottom one */ --c1w: @r(38, 62); --c1h: @r(18, 30); --c2w: @r(22, 40); --off1: @r(-4, 4); --off2: @r(-7, 7); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: calc((50 - @var(--c1w) / 2 + @var(--off1)) * 1%); bottom: 8%; width: calc(@var(--c1w) * 1%); height: calc(@var(--c1h) * 1%); border-radius: 46%; background: var(--stone1); transition: ease 700ms; } :after { content: ''; position: absolute; left: calc((50 - @var(--c2w) / 2 + @var(--off2)) * 1%); bottom: calc(8% + @var(--c1h) * 0.85%); width: calc(@var(--c2w) * 1%); height: var(--c2h); border-radius: 46%; background: var(--stone2); transition: ease 700ms; } }`,
  },
  {
    name: 'Halftone',
    slug: 'halftone',
    order: 116,
    description:
      'A halftone ramp printed top to bottom — dots grow with each row, and the whole screen shivers as every dot re-jitters per seed.',
    palette: ['#FAF7F0', '#232529', '#E6437D'],
    colors: { min: 2, max: 3, default: 2 },
    gridDefault: '10x15',
    freqDefault: 1,
    thumb: { grid: '7x7', frequency: 0.95 },
    vars: `--dot: @p(var(--color1), var(--color1), var(--color1), var(--color1), var(--color2));`,
    rule: `/* dot size ramps with the row, jittered by one emitted factor per cell */ --hd: calc((10 + 62 * @y / @Y) * @r(0.55, 1.25)); @random(\${shapeFrequency}) { :after { content: ''; position: absolute; @size: calc(@var(--hd) * 1%); left: calc(50% - @var(--hd) * 0.5%); top: calc(50% - @var(--hd) * 0.5%); border-radius: 50%; background: var(--dot); transition: ease 600ms; } }`,
  },
  {
    name: 'Cog',
    slug: 'cog',
    order: 117,
    white: true,
    description:
      'Brass gears with dashed teeth meshing in the dark — every redraw turns the whole movement by a few degrees.',
    palette: ['#1F1B16', '#C9A227', '#A8763E', '#8C8C88', '#E0CB8F'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--mesh: @rand(180deg);`,
    rule: `/* teeth ring and hub share one emitted brass tone */ --gear: @p(var(--color1), var(--color2), var(--color3), var(--color4)); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; inset: 12%; border-radius: 50%; border: calc(@rand(30, 52) * 1px / @Y) dashed @var(--gear); transform: rotate(var(--mesh)); transition: ease 900ms; } :after { content: ''; position: absolute; inset: 38%; border-radius: 50%; border: calc(22px / @Y) solid @var(--gear); opacity: 0.7; transition: ease 900ms; } }`,
  },
  {
    name: 'Lyra',
    slug: 'lyra',
    order: 118,
    white: true,
    description:
      'Binary stars joined by faint beams — one shared angle keeps each pair rigid while the constellation re-forms on every redraw.',
    palette: ['#0D1226', '#4A5A8A', '#E8F1FF', '#97F4FF', '#FF8FB8'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: ``,
    rule: `/* one emitted angle (radians) drives the beam rotation and the partner-star trig, keeping each pair rigid */ --lar: @r(0, 6.2832); --llp: @r(16, 36); --sz: @r(7, 13); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: 50%; top: 50%; width: calc(@var(--llp) * 10px / @Y); height: 1.5px; background: var(--color2); opacity: 0.6; transform: rotate(calc(@var(--lar) * 57.2958deg)); transform-origin: 0% 50%; transition: ease 800ms; } :after { content: ''; position: absolute; @size: calc(@var(--sz) * 1%); left: calc(50% - @var(--sz) * 0.5%); top: calc(50% - @var(--sz) * 0.5%); border-radius: 50%; background: var(--color3); box-shadow: calc(cos(@var(--lar) * 1rad) * @var(--llp) * 10px / @Y) calc(sin(@var(--lar) * 1rad) * @var(--llp) * 10px / @Y) 0 calc(-8px / @Y) var(--color4); transition: ease 800ms; } }`,
  },
  {
    name: 'Cumulus',
    slug: 'cumulus',
    order: 119,
    description:
      'Fair-weather clouds drifting across a noon sky, the occasional sun breaking through — each redraw reshapes every puff.',
    palette: ['#A7D8F0', '#FFFFFF', '#EAF7FF', '#FFD66B', '#7FB6D9'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.8,
    thumb: { grid: '4x4', frequency: 0.8 },
    vars: ``,
    rule: `/* the upper lobe rides on the emitted geometry of the base lobe and shares its tone */ --cloud: @p(var(--color1), var(--color1), var(--color2)); --cl: @r(0, 36); --cw: @r(44, 70); --ch: @r(20, 32); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: calc(@var(--cl) * 1%); bottom: 20%; width: calc(@var(--cw) * 1%); height: calc(@var(--ch) * 1%); border-radius: 99px; background: @var(--cloud); transition: ease 800ms; } :after { content: ''; position: absolute; left: calc((@var(--cl) + @var(--cw) * 0.28) * 1%); bottom: calc(20% + @var(--ch) * 0.5%); width: calc(@var(--cw) * 0.55%); height: calc(@var(--ch) * 0.8%); border-radius: 99px; background: @var(--cloud); transition: ease 800ms; } } @random(0.1) { background: radial-gradient(circle at 70% 26%, var(--color3) 0 12%, transparent 13%); }`,
  },
  {
    name: 'Elbow',
    slug: 'elbow',
    order: 120,
    description:
      'Fat pastel pipe elbows re-plumbing themselves quarter-turn by quarter-turn — the network reroutes on every redraw.',
    palette: ['#FBF6EF', '#FF8AAE', '#7EC8E3', '#FFC75F', '#9D89F2'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.92 },
    vars: `--pipe: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --bend: @p(0deg, 90deg, 180deg, 270deg);`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; inset: 0; border: solid var(--pipe); border-width: calc(170px / @Y) calc(170px / @Y) 0 0; border-radius: 0 100% 0 0; transform: rotate(var(--bend)); box-sizing: border-box; transition: ease 600ms; } }`,
  },
  {
    name: 'Trellis',
    slug: 'trellis',
    order: 121,
    description:
      'A fixed garden lattice with bright beads that glide along the diagonals — only the blooms move when the seed changes.',
    palette: ['#F6F3EB', '#355E3B', '#E6437D', '#F5B82E', '#D94F30'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 0.8,
    thumb: { grid: '6x6', frequency: 0.8 },
    vars: `--bead: @p(var(--color2), var(--color3), var(--color4));`,
    rule: `/* the bead's top mirrors its emitted left onto one diagonal, so it glides along the lattice */ --tp: @r(15, 85); --branch: @p(1, -1); background: linear-gradient(45deg, transparent calc(50% - 1px), var(--color1) calc(50% - 1px) calc(50% + 1px), transparent calc(50% + 1px)), linear-gradient(-45deg, transparent calc(50% - 1px), var(--color1) calc(50% - 1px) calc(50% + 1px), transparent calc(50% + 1px)); @random(\${shapeFrequency}) { :after { content: ''; position: absolute; @size: 13%; left: calc(@var(--tp) * 1% - 6.5%); top: calc((50 + (@var(--tp) - 50) * @var(--branch)) * 1% - 6.5%); border-radius: 50%; background: var(--bead); transition: ease 700ms; } }`,
  },
  {
    name: 'Frond',
    slug: 'frond',
    order: 122,
    description:
      'Three-bladed palm fronds planted across the canvas — the blades fan open and closed and lean with each redraw.',
    palette: ['#EAF5E6', '#2E7D52', '#55A86F', '#8FCF9F', '#C7E8C9'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--lean: @rand(-12deg, 12deg);`,
    rule: `/* the side blades mirror one emitted spread angle and share the center blade's color */ --blade: @p(var(--color1), var(--color2), var(--color3)); --spread: @r(16, 40); @random(\${shapeFrequency}) { width: 7%; height: 70%; margin: 15% 46.5%; border-radius: 99px; background: @var(--blade); transform-origin: 50% 100%; transform: rotate(var(--lean)); :before { content: ''; position: absolute; inset: 0; border-radius: 99px; background: @var(--blade); transform: rotate(calc(@var(--spread) * 1deg)); transform-origin: 50% 100%; transition: ease 700ms; } :after { content: ''; position: absolute; inset: 0; border-radius: 99px; background: @var(--blade); transform: rotate(calc(@var(--spread) * -1deg)); transform-origin: 50% 100%; transition: ease 700ms; } } transition: ease 700ms;`,
  },
  {
    name: 'Abacus',
    slug: 'abacus',
    order: 123,
    description:
      'Beads sliding along their rods to new positions on every redraw — an abacus forever recounting itself.',
    palette: ['#F7EFE2', '#6B4F35', '#D94F30', '#2E86AB', '#E8B44F', '#5B8C5A'],
    colors: { min: 2, max: 6, default: 6 },
    gridDefault: '8x12',
    freqDefault: 0.9,
    thumb: { grid: '5x5', frequency: 0.9 },
    vars: `--bead1: @p(var(--color2), var(--color3), var(--color4), var(--color5)); --bead2: @p(var(--color2), var(--color3), var(--color4), var(--color5)); --abx1: @rand(2%, 62%); --abx2: @rand(2%, 62%); --show2: @p(0, 1, 1);`,
    rule: `background: linear-gradient(transparent 48.75%, var(--color1) 48.75% 51.25%, transparent 51.25%); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; width: 17%; height: 30%; left: var(--abx1); top: 35%; border-radius: 40%; background: var(--bead1); transition: ease 600ms; } :after { content: ''; position: absolute; width: 17%; height: 30%; left: var(--abx2); top: 35%; border-radius: 40%; background: var(--bead2); opacity: var(--show2); transition: ease 600ms; } }`,
  },
  {
    name: 'Bento',
    slug: 'bento',
    order: 124,
    description:
      'Lacquered lunch boxes whose partitions slide from seed to seed — compartments widen, shrink and trade their fillings.',
    palette: ['#2B1E1A', '#E2543E', '#88A872', '#F5DD8A', '#F3EBDB'],
    colors: { min: 2, max: 5, default: 5 },
    white: true,
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.95 },
    vars: `--dishA: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --dishB: @p(var(--color1), var(--color2), var(--color3), var(--color4)); --sub: @rand(40%, 92%);`,
    rule: `/* both compartments share one emitted divider position, so the wall slides as a unit */ --cut: @r(28, 64); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: 6%; top: 6%; width: calc(@var(--cut) * 1% - 9%); height: 88%; border-radius: 7%; background: var(--dishA); transition: ease 600ms; } :after { content: ''; position: absolute; left: calc(@var(--cut) * 1% + 3%); bottom: 6%; width: calc(91% - @var(--cut) * 1%); height: var(--sub); border-radius: 7%; background: var(--dishB); transition: ease 600ms; } }`,
  },
  {
    name: 'Decant',
    slug: 'decant',
    order: 125,
    description:
      'Apothecary vessels filling and emptying — liquid levels rise and fall behind steady glass outlines on every redraw.',
    palette: ['#F4F1E8', '#6B6F66', '#D98E32', '#2E8C7F', '#7E4A8C'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: `--liquid: @p(var(--color2), var(--color3), var(--color4)); --lvl: @rand(8%, 60%);`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; inset: 8% 24%; border: 2px solid var(--color1); border-radius: 14% 14% 26% 26%; opacity: 0.75; transition: ease 700ms; } :after { content: ''; position: absolute; left: calc(24% + 2px); right: calc(24% + 2px); bottom: calc(8% + 2px); height: var(--lvl); background: var(--liquid); border-radius: 4% 4% 24% 24%; opacity: 0.85; transition: ease 700ms; } }`,
  },
  {
    name: 'Seigaiha',
    slug: 'seigaiha',
    order: 126,
    white: true,
    description:
      'Wave crests bobbing over an indigo sea, after the traditional seigaiha motif — each crest rides at its own height per seed.',
    palette: ['#1B3A5C', '#5B8FB9', '#9EC9E8', '#EAF4FB', '#3E8BFF'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '5x5', frequency: 0.95 },
    vars: `--crest1: @p(var(--color1), var(--color2), var(--color3)); --crest2: @p(var(--color2), var(--color3)); --cy1: @rand(20%, 55%); --cy2: @rand(45%, 80%);`,
    rule: `--cs1: @r(70, 95); --cs2: @r(40, 60); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; @size: calc(@var(--cs1) * 1%); left: calc(50% - @var(--cs1) * 0.5%); top: var(--cy1); border: calc(30px / @Y) solid var(--crest1); border-radius: 50%; clip-path: inset(0 0 52% 0); box-sizing: border-box; transition: ease 700ms; } :after { content: ''; position: absolute; @size: calc(@var(--cs2) * 1%); left: calc(50% - @var(--cs2) * 0.5%); top: var(--cy2); border: calc(22px / @Y) solid var(--crest2); border-radius: 50%; clip-path: inset(0 0 52% 0); box-sizing: border-box; transition: ease 700ms; } }`,
  },
  {
    name: 'Grain',
    slug: 'grain',
    order: 127,
    white: true,
    description:
      'Silver film grain breathing in the dark — every cell fades to its own new exposure, slowly, like static settling.',
    palette: ['#0F0F10', '#E8E6E1', '#E63946'],
    colors: { min: 2, max: 3, default: 2 },
    gridDefault: '10x15',
    freqDefault: 1,
    thumb: { grid: '8x8', frequency: 0.95 },
    vars: `--g1: @rand(0.04, 0.8); --g2: @p(0%, 0%, 0%, 50%);`,
    rule: `@random(\${shapeFrequency}) { margin: 1px; background: var(--color1); opacity: var(--g1); border-radius: var(--g2); } @random(0.03) { background: var(--color2); opacity: 0.9; } transition: ease 900ms;`,
  },
  {
    name: 'Misprint',
    slug: 'misprint',
    order: 128,
    description:
      'Two riso plates sliding in and out of register — mirrored offsets pull the inks apart and let them overlap into new blends.',
    palette: ['#FBF7EE', '#FF4D6D', '#2E86AB', '#F5B82E', '#7E4A8C'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.92 },
    vars: `--plate1: @p(var(--color1), var(--color3)); --plate2: @p(var(--color2), var(--color4));`,
    rule: `/* the two plates share one emitted offset, mirrored, so they slide apart symmetrically */ --mx: @r(-10, 10); --my: @r(-10, 10); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; @size: 58%; left: calc(21% + @var(--mx) * 1%); top: calc(21% + @var(--my) * 1%); border-radius: 50%; background: var(--plate1); opacity: 0.72; mix-blend-mode: multiply; transition: ease 700ms; } :after { content: ''; position: absolute; @size: 58%; left: calc(21% - @var(--mx) * 1%); top: calc(21% - @var(--my) * 1%); border-radius: 50%; background: var(--plate2); opacity: 0.72; mix-blend-mode: multiply; transition: ease 700ms; } }`,
  },
  {
    name: 'Stepwell',
    slug: 'stepwell',
    order: 129,
    description:
      'Nested sandstone terraces descending toward a vanishing point that drifts with every redraw — an ancient stepwell seen from above.',
    palette: ['#E8D5B5', '#C49B61', '#9C6B3E', '#6E4426', '#3E2A1C'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.95 },
    vars: `--wellA: @p(var(--color1), var(--color2)); --wellB: @p(var(--color2), var(--color3)); --wellC: @p(var(--color3), var(--color4));`,
    rule: `/* every terrace drifts toward the same emitted vanishing point */ --vx: @r(-9, 9); --vy: @r(-9, 9); @random(\${shapeFrequency}) { background: var(--wellA); :before { content: ''; position: absolute; left: calc(16% + @var(--vx) * 1%); top: calc(16% + @var(--vy) * 1%); right: calc(16% - @var(--vx) * 1%); bottom: calc(16% - @var(--vy) * 1%); background: var(--wellB); transition: ease 700ms; } :after { content: ''; position: absolute; left: calc(34% + @var(--vx) * 2%); top: calc(34% + @var(--vy) * 2%); right: calc(34% - @var(--vx) * 2%); bottom: calc(34% - @var(--vy) * 2%); background: var(--wellC); transition: ease 700ms; } } transition: ease 700ms;`,
  },
  {
    name: 'Regatta',
    slug: 'regatta',
    order: 130,
    description:
      'A fleet of little sailboats heeling in the breeze — sails re-rake and hulls rock to new angles with every redraw.',
    palette: ['#DCEFF7', '#2F4156', '#FFFFFF', '#FF6B6B', '#F5B82E'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.8,
    thumb: { grid: '4x4', frequency: 0.8 },
    vars: `--sail: @p(var(--color2), var(--color3), var(--color4)); --luff: @rand(8%, 60%);`,
    rule: `/* sail and hull heel together on one emitted angle */ --heel: @r(-9, 9); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: 24%; bottom: 30%; width: 40%; height: 44%; background: var(--sail); clip-path: polygon(var(--luff) 0%, 100% 100%, 0% 100%); transform: rotate(calc(@var(--heel) * 1deg)); transform-origin: 50% 100%; transition: ease 700ms; } :after { content: ''; position: absolute; left: 17%; bottom: 17%; width: 58%; height: 13%; background: var(--color1); border-radius: 0 0 99px 99px; transform: rotate(calc(@var(--heel) * 1deg)); transition: ease 700ms; } }`,
  },
  {
    name: 'Flit',
    slug: 'flit',
    order: 131,
    white: true,
    description:
      'Moths at dusk, wings flapping in mirrored pairs — every redraw catches them at a different beat of the wing.',
    palette: ['#2E2440', '#D8B4E2', '#B388EB', '#F2D7EE', '#8E6BD9'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 0.9,
    thumb: { grid: '4x4', frequency: 0.9 },
    vars: ``,
    rule: `/* both wings mirror one emitted flap angle and share color and outer radius */ --wing: @p(var(--color1), var(--color2), var(--color3)); --flap: @r(-14, 20); --wr: @r(40, 70); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: 16%; top: 28%; width: 32%; height: 44%; background: @var(--wing); border-radius: calc(@var(--wr) * 1%) 12% 60% 40% / 60% 30% 70% 40%; transform: rotate(calc(@var(--flap) * 1deg)); transform-origin: 100% 50%; transition: ease 700ms; } :after { content: ''; position: absolute; left: 52%; top: 28%; width: 32%; height: 44%; background: @var(--wing); border-radius: 12% calc(@var(--wr) * 1%) 40% 60% / 30% 60% 40% 70%; transform: rotate(calc(@var(--flap) * -1deg)); transform-origin: 0% 50%; transition: ease 700ms; } }`,
  },
  {
    name: 'Orchard',
    slug: 'orchard',
    order: 132,
    description:
      'Rows of little fruit trees — crowns swell through the seasons and trunks stretch a bit taller with every redraw.',
    palette: ['#F3F7E9', '#6B4F35', '#7FB069', '#E2543E', '#F5B82E'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 0.9,
    thumb: { grid: '5x5', frequency: 0.9 },
    vars: `--crownC: @p(var(--color2), var(--color2), var(--color3), var(--color4));`,
    rule: `/* the crown sits on the emitted trunk height */ --trunk: @r(16, 34); --crown: @r(36, 64); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: 47.5%; bottom: 8%; width: 5%; height: calc(@var(--trunk) * 1%); background: var(--color1); border-radius: 99px; transition: ease 700ms; } :after { content: ''; position: absolute; @size: calc(@var(--crown) * 1%); left: calc(50% - @var(--crown) * 0.5%); bottom: calc(4% + @var(--trunk) * 1%); border-radius: 50% 50% 46% 46%; background: var(--crownC); transition: ease 700ms; } }`,
  },
  {
    name: 'Quartz',
    slug: 'quartz',
    order: 133,
    white: true,
    description:
      'Amethyst crystals growing from the cave floor — prisms stretch, lean and glint differently under every seed.',
    palette: ['#1E1433', '#9D5BD2', '#C490FF', '#6A3BB5', '#E8DAFF'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '6x9',
    freqDefault: 1,
    thumb: { grid: '4x4', frequency: 0.95 },
    vars: `--gem1: @p(var(--color1), var(--color2), var(--color3)); --gem2: @p(var(--color1), var(--color2), var(--color3)); --q1: @rand(36%, 92%); --q2: @rand(24%, 64%); --qt1: @rand(-10deg, 4deg); --qt2: @rand(-4deg, 10deg);`,
    rule: `@random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: 24%; bottom: 0; width: 24%; height: var(--q1); background: var(--gem1); clip-path: polygon(50% 0%, 100% 20%, 100% 100%, 0% 100%, 0% 20%); opacity: 0.88; transform: rotate(var(--qt1)); transform-origin: 50% 100%; transition: ease 700ms; } :after { content: ''; position: absolute; left: 52%; bottom: 0; width: 24%; height: var(--q2); background: var(--gem2); clip-path: polygon(50% 0%, 100% 20%, 100% 100%, 0% 100%, 0% 20%); opacity: 0.72; transform: rotate(var(--qt2)); transform-origin: 50% 100%; transition: ease 700ms; } }`,
  },
  {
    name: 'Sprout',
    slug: 'sprout',
    order: 134,
    description:
      'Seedlings unfurling their first pair of leaves — every redraw catches germination at a different moment.',
    palette: ['#F0F7EE', '#4CAF6E', '#7BD88F', '#6B4F35', '#2E7D52'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 0.9,
    thumb: { grid: '5x5', frequency: 0.9 },
    vars: ``,
    rule: `/* both seed leaves unfurl by one emitted angle and share a tone */ --leafA: @p(var(--color1), var(--color2), var(--color4)); --germ: @r(0, 26); --soil: @r(20, 40); @random(\${shapeFrequency}) { :before { content: ''; position: absolute; left: 19%; bottom: 26%; width: 31%; height: 42%; background: @var(--leafA); clip-path: @shape(drop); transform: rotate(calc(-24deg - @var(--germ) * 1deg)); transform-origin: 100% 100%; transition: ease 700ms; } :after { content: ''; position: absolute; left: 50%; bottom: 26%; width: 31%; height: 42%; background: @var(--leafA); clip-path: @shape(drop); transform: rotate(calc(24deg + @var(--germ) * 1deg)); transform-origin: 0% 100%; transition: ease 700ms; } } @random(0.5) { background: radial-gradient(ellipse at 50% 100%, var(--color3) 0 calc(@var(--soil) * 1%), transparent calc(@var(--soil) * 1% + 1%)); }`,
  },
  {
    name: 'Zipper',
    slug: 'zipper',
    order: 135,
    description:
      'Rows of rounded teeth meshing from alternate sides — the zip opens and closes a little differently on every redraw.',
    palette: ['#F4EFE6', '#2F4156', '#E2543E', '#F5B82E', '#2BB3A3'],
    colors: { min: 2, max: 5, default: 5 },
    gridDefault: '8x12',
    freqDefault: 1,
    thumb: { grid: '6x6', frequency: 0.95 },
    vars: `--toothA: @p(var(--color1), var(--color1), var(--color2), var(--color3)); --zw: @rand(42%, 80%);`,
    rule: `--zg: @r(0, 9); @random(\${shapeFrequency}) { :after { content: ''; position: absolute; left: 0; top: calc(16% + @var(--zg) * 1%); width: var(--zw); height: calc(68% - @var(--zg) * 2%); background: var(--toothA); border-radius: 0 26% 26% 0; transition: ease 600ms; } } @match(y % 2 == 0) { :after { left: auto; right: 0; border-radius: 26% 0 0 26%; } }`,
  },
  {
    name: 'Flock',
    slug: 'flock',
    order: 136,
    description:
      'A murmuration over a warm evening sky — chevron birds wheel, bank and regroup somewhere new on every redraw.',
    palette: ['#F2E3D5', '#2E2A33', '#C96F3B', '#8A8273'],
    colors: { min: 2, max: 4, default: 4 },
    gridDefault: '8x12',
    freqDefault: 0.8,
    thumb: { grid: '6x6', frequency: 0.8 },
    vars: `--bird: @p(var(--color1), var(--color1), var(--color1), var(--color2)); --fx: @rand(2%, 66%); --fy: @rand(2%, 66%); --head: @rand(-40deg, 40deg); --depth: @rand(0.5, 1.1); --fo: @rand(0.55, 1);`,
    rule: `@random(\${shapeFrequency}) { :after { content: ''; position: absolute; left: var(--fx); top: var(--fy); width: @rand(18%, 36%); aspect-ratio: 1.61; background: var(--bird); clip-path: polygon(0% 0%, 50% 78%, 100% 0%, 100% 32%, 50% 100%, 0% 32%); transform: rotate(var(--head)) scale(var(--depth)); opacity: var(--fo); transition: ease 800ms; } }`,
  },
];
